### ISSUE TITLE
[ Frontend ] Better css for password input 

### ISSUE THREAD

**Issue by yannis-mlgrn** [dmdhrumilmistry/GooglePhish#20]
## The problem ;
When we typing in the password input, the placeholder moving up and go above the email text like this : 

![the login popup](https://user-images.githubusercontent.com/48618655/210181153-0e8aebb0-e1c8-423e-b50d-ce0709892e9a.png)

## How we can resolve it : 
I suggest to add some css specs like margin to avoid this problem

**Comment by dmdhrumilmistry** [comment]
@yannis-mlgrn okay great, I'll review it and merge ASAP, if changes aren't breaking anything.
