### ISSUE TITLE
CSRF verification failed

### ISSUE THREAD

**Issue by barbosa7** [dmdhrumilmistry/GooglePhish#29]
When I run the code and open it on localhost it works fine, but when I try to do it with a tunneling service (I tried localhost.run and ngrok) it loads the first page but after I click next or enter it should go to the page where the user writes the password but instead this page appears:

![Screenshot 2023-08-11 at 17 58 46](https://github.com/dmdhrumilmistry/GooglePhish/assets/81977215/14b82454-bba9-4ecd-acf4-7e5609c70f50)

I'm not sure why this is happening, did I make a mistake setting this up or is it just a bug in the code itself? Is there any way for me to fix it? I am not trying to do anything illegal, a friend of mine owns a company and gave me an email list for me to try to phish his employers on their work emails to see if they are respecting the it security rules he implemented, so obviously they can't know what I am doing and a page like this popping up would make sure that it doesn't work, but there is nothing illegal going on. Thanks in advance.

**Comment by barbosa7** [comment]
I think I managed to fix it by adding this to the settings.py file

![Screenshot 2023-08-11 at 18 43 12](https://github.com/dmdhrumilmistry/GooglePhish/assets/81977215/f135d359-41e4-458c-affe-5d6bceee3340)

you might want to write that in the readme together with the rest of the documentation so that it's easier for other people to solve it.

**Comment by dmdhrumilmistry** [comment]
Hi @barbosa7, thanks for looking into the issue, I'll surely update the readme.
