### ISSUE TITLE
pre-build arm64 Docker containers (enhancement)

### ISSUE THREAD

**Issue by trueToastedCode** [dmdhrumilmistry/GooglePhish#34]
Apparently you guys only support x86-64 for the pre-build Docker containers. It would be nice, if there were also builds for arm64 for the folks using MacBooks or Raspberry pi's.

<img width="700" src="https://github.com/dmdhrumilmistry/GooglePhish/assets/44642574/27890b63-f08b-4b31-b829-0952440c9608">

**Comment by dmdhrumilmistry** [comment]
Yes, I'm planning to add this to CICD. For now, you can build a docker image for ARM device using below command from README.md file:

```bash
docker build -t googlephish . 
```

> add `sudo` if required
