### ISSUE TITLE
login with other domains than @gmail.com

### ISSUE THREAD

**Issue by zeini321** [dmdhrumilmistry/GooglePhish#41]
Hi @dmdhrumilmistry,

I appreciate your project a lot, but I noticed that when I log in with another domain (e.g. email@domain.live) it'll submit it as email@gmail.com, also on passwd.html it replaces any domain with gmail.com.

Great work !

**Comment by dmdhrumilmistry** [comment]
Hi @zeini321,

I intentionally created it to accept only Gmail accounts. I'll try to update source code to accept any domain feature over the weekend.

Thanks for raising the issue and using the project.
