### ISSUE TITLE
Updating Env

### ISSUE THREAD

**Issue by dmdhrumilmistry** [dmdhrumilmistry/GooglePhish#54]
i m just learning here.... 
how do i update the Env File template?
any commands to do in terminal ?

_Originally posted by @jimblonde100 in https://github.com/dmdhrumilmistry/GooglePhish/issues/35#issuecomment-2226989340_

**Comment by dmdhrumilmistry** [comment]
@jimblonde100 you can create an env file in the project's root directory with the below command:

```bash
export SECRET_KEY=$(python3 generate_new_key.py) 
touch .env
cat > .env <<EOL
DJANGO_SECRET_KEY=$SECRET_KEY
DEBUG=False
ALLOWED_HOSTS=*
CSRF_TRUSTED_ORIGINS=http://localhost:8000
EOL
```

**Comment by jimblonde100** [comment]
hi thanks for the quick reply... 
i have done the above mentioned steps. 

now how do i update the .env file?

**Comment by dmdhrumilmistry** [comment]
> hi thanks for the quick reply... i have done the above mentioned steps.
> 
> now how do i update the .env file?

It's as simple as editing a file. You can use text editor to edit `.env` file as change values as per your requirement.

**Comment by jimblonde100** [comment]
finally got it... 
being a n00b... i forgot to show hidden files.. sorry.. 
and thanks for the instant updates !
