### ISSUE TITLE
run on replit?

### ISSUE THREAD

**Issue by animecat7** [dmdhrumilmistry/GooglePhish#6]
can you make it replit friendly

![Screenshot 2022-07-17 10 17 34 PM](https://user-images.githubusercontent.com/97673666/179449328-bfb3565e-89da-4019-85a3-becc11a6585d.png)
it gives these errors

**Comment by dmdhrumilmistry** [comment]
Can you specify commands and steps used in the process?

**Comment by dmdhrumilmistry** [comment]
I'm closing the issue due to inactivity
