### ISSUE TITLE
Docker image is not yet updated

### ISSUE THREAD

**Issue by yannis-mlgrn** [dmdhrumilmistry/GooglePhish#7]
In your documentation you said that we can use your docker image. but it's not updated we have the old form and the admin dashboard doesn't exist at `http://localhost:8000/pawned`

**Comment by dmdhrumilmistry** [comment]
yikes, I might have missed to push the docker image to dockerhub. I'll try to fix it soon.

**Comment by yannis-mlgrn** [comment]
I can add docker secrets ( environment variables ) for username, password and email. This will allow the user to specify his credentials before build the image, and i think is a good solution because this credentials will not present in hard in the Dockerfile.

**Comment by dmdhrumilmistry** [comment]
Docker container image has been updated on [DockerHub](https://hub.docker.com/r/dmdhrumilmistry/googlephish)
