### ISSUE TITLE
[ Improvement ] Default credential not specify in docker documentation 

### ISSUE THREAD

**Issue by yannis-mlgrn** [dmdhrumilmistry/GooglePhish#8]
We can specify the defaults admin credential in the docker documentation to avoid people to lost time to search it in the `Dockerfile`

**Comment by yannis-mlgrn** [comment]
@dmdhrumilmistry, you're welcome, indeed it will be a good feature!!  It's a great project, if you want help in certain tasks, don't hesitate to create issues!  It will be with pleasure that I can try to help you 🤙🏻

**Comment by dmdhrumilmistry** [comment]
@yannis-mlgrn if you wanna contribute then I can assign it to you, let me know regarding the same

**Comment by yannis-mlgrn** [comment]
@dmdhrumilmistry, I can add docker secrets ( environment variables ) for username, password and email. This will allow the user to specify his credentials before build the image, and i think is a good solution because this credentials will not present in hard in the Dockerfile.

**Comment by dmdhrumilmistry** [comment]
okay, I'm assigning this task to you in a new issue. You can make the necessary changes and pull a PR. I'll merge it after review.
